---
title: "Programa de Prevención & Control del Dengue | 2024"
format: 
  dashboard:
      nav-buttons: [twitter, github, facebook]
theme: custom.scss
---

```{r setup}
library(sf)
mapview::mapviewOptions(default = TRUE,
                        basemaps.color.shuffle = FALSE)
load("/Users/felipedzul/Library/CloudStorage/OneDrive-Personal/proyects/geocoding_mex/2024/8.RData/denmex_2024.RData")
library(magrittr)
```



# [**Cadenas de Transmisión**]{style="font-size:8pt"}

::: panel-tabset

### [**Morelia**]{style="color:#990000"}

```{r}
denhotspots::transmission_chains_map(geocoded_dataset = z,
                                     cve_edo = "16",
                                     locality = "Morelia",
                                     dengue_cases = "Confirmado")
```


### [**Uruapan**]{style="color:#990000"}

```{r}
denhotspots::transmission_chains_map(geocoded_dataset = z,
                                     cve_edo = "16",
                                     locality = "Uruapan",
                                     dengue_cases = "Confirmado")
```


### [**Lazaro Cardenas**]{style="color:#990000"}

```{r}
denhotspots::transmission_chains_map(geocoded_dataset = z,
                                     cve_edo = "16",
                                     locality = "Ciudad Lazaro Cardenas",
                                     dengue_cases = "Confirmado")
```

:::



# [**Mapas de Calor**]{style="font-size:8pt"}

::: panel-tabset

### [**Morelia**]{style="color:#990000"}

```{r}
densnv::mp_heatmap(geocoded_datasets = z,
                   cve_edo = "16",
                   locality = "Morelia",
                   status_caso = c(1, 2),
                   week = c(1:53),
                   zoom = NULL,
                   map_type = NULL,
                   alpha = 0.6,
                   static = FALSE,
                   palette = viridis::turbo)
```


### [**Uruapan**]{style="color:#990000"}

```{r}
densnv::mp_heatmap(geocoded_datasets = z,
                   cve_edo = "16",
                   locality = "Uruapan",
                   status_caso = c(1, 2),
                   week = c(1:53),
                   zoom = NULL,
                   map_type = NULL,
                   alpha = 0.6,
                   static = FALSE,
                   palette = viridis::turbo)
```

### [**Lazaro Cardenas**]{style="color:#990000"}

```{r}
densnv::mp_heatmap(geocoded_datasets = z,
                   cve_edo = "16",
                   locality = "Ciudad Lazaro Cardenas",
                   status_caso = c(1, 2),
                   week = c(1:53),
                   zoom = NULL,
                   map_type = NULL,
                   alpha = 0.6,
                   static = FALSE,
                   palette = viridis::turbo)
```

:::


# [**Log-Gaussian Cox Processes**]{style="font-size:8pt"}

::: panel-tabset

### [**Morelia**]{style="color:#990000"}

```{r}
load("~/Dropbox/r_developments/r_dashboards/netlify/transmission_chains/transmission_chains_2024/lgcp_morelia_2024.RData")
lgcp_morelia_2024$map
```


### [**Uruapan**]{style="color:#990000"}

```{r}
load("~/Dropbox/r_developments/r_dashboards/netlify/transmission_chains/transmission_chains_2024/lgcp_uruapan_2024.RData")

lgcp_uruapan_2024$map

```



:::
